# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'twitter-scraper.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(978, 410)

        self.Output_Window = QtWidgets.QTextBrowser(Form)
        self.Output_Window.setGeometry(QtCore.QRect(310, 0, 771, 411))
        self.Output_Window.setObjectName("Output_Window")

        self.ID_box = QtWidgets.QLineEdit(Form)
        self.ID_box.setGeometry(QtCore.QRect(110, 40, 161, 20))
        self.ID_box.setObjectName("ID_box")

        self.Handle = QtWidgets.QLabel(Form)
        self.Handle.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.Handle.setObjectName("Handle")

        self.Query_box = QtWidgets.QLineEdit(Form)
        self.Query_box.setGeometry(QtCore.QRect(110, 70, 161, 20))
        self.Query_box.setObjectName("Query_box")

        self.Search_Query = QtWidgets.QLabel(Form)
        self.Search_Query.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.Search_Query.setObjectName("Search_Query")

        self.Mic_Search = QtWidgets.QPushButton(Form)
        self.Mic_Search.setGeometry(QtCore.QRect(280, 70, 21, 23))
        self.Mic_Search.setText("")
        self.Mic_Search.setObjectName("Mic_Search")

        self.Submit_req = QtWidgets.QPushButton(Form)
        self.Submit_req.setGeometry(QtCore.QRect(70, 160, 161, 31))
        self.Submit_req.setObjectName("Submit_req")

        self.req_history = QtWidgets.QPushButton(Form)
        self.req_history.setGeometry(QtCore.QRect(60, 200, 181, 23))
        self.req_history.setObjectName("req_history")

        self.Search_by = QtWidgets.QLabel(Form)
        self.Search_by.setGeometry(QtCore.QRect(70, 230, 61, 16))
        self.Search_by.setObjectName("Search_by")
        
        self.max_results = QtWidgets.QLineEdit(Form)
        self.max_results.setGeometry(QtCore.QRect(110, 100, 81, 20))
        self.max_results.setObjectName("max_results")
        
        self.max_results_label = QtWidgets.QLabel(Form)
        self.max_results_label.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.max_results_label.setObjectName("max_results_label")
        
        self.by_TwitterUser = QtWidgets.QRadioButton(Form)
        self.by_TwitterUser.setGeometry(QtCore.QRect(100, 250, 101, 17))
        self.by_TwitterUser.setObjectName("by_TwitterUser")
        
        self.by_TwitterAll = QtWidgets.QRadioButton(Form)
        self.by_TwitterAll.setGeometry(QtCore.QRect(100, 270, 121, 17))
        self.by_TwitterAll.setObjectName("by_TwitterAll")
        
        self.Exclusion = QtWidgets.QLabel(Form)
        self.Exclusion.setGeometry(QtCore.QRect(70, 300, 47, 13))
        self.Exclusion.setObjectName("Exclusion")
        
        self.exclu_Retweets = QtWidgets.QCheckBox(Form)
        self.exclu_Retweets.setGeometry(QtCore.QRect(100, 320, 70, 17))
        self.exclu_Retweets.setObjectName("exclu_Retweets")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Handle.setText(_translate("Form", "Twitter Handle : "))
        self.Search_Query.setText(_translate("Form", "Search Query:"))
        self.Submit_req.setText(_translate("Form", "Submit request"))
        self.req_history.setText(_translate("Form", "Show request history"))
        self.Search_by.setText(_translate("Form", "Search By:"))
        self.max_results_label.setText(_translate("Form", "Maximum results:  "))
        self.by_TwitterUser.setText(_translate("Form", "By Twitter User"))
        self.by_TwitterAll.setText(_translate("Form", "The Whole of Twitter"))
        self.Exclusion.setText(_translate("Form", "Exclude: "))
        self.exclu_Retweets.setText(_translate("Form", "Retweets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
